---
deployment:
  tasks:
    # Set the deployment target directory
    - export DEPLOYPATH=$HOME/dangts_website
    
    # Copy project files from the repository to the deployment path
    - /bin/cp -R . $DEPLOYPATH
    
    # Make the deployment bash script executable
    - /bin/chmod +x $DEPLOYPATH/deploy.sh
    
    # Execute the build and asset setup script
    - /bin/bash $DEPLOYPATH/deploy.sh $DEPLOYPATH
